name: snap
on:
  push:
    branches:
      - content-sharing
  pull_request:
    branches:
      - content-sharing
  workflow_dispatch:
  workflow_call:

jobs:
  content-sharing-snap:
    uses: ubuntu-robotics/snap_workflows/.github/workflows/build-install-test-snap.yaml@main
    env:
      SNAPCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS: 1
    with:
      branch-name: content-sharing
      snap-name: ros2-talker-listener
